#!/usr/bin/perl -w -s
use Biblio::Catalog::BibTeX;

my $file = shift || die "I need a filename...";

my $obj = Biblio::Catalog::BibTeX::loadBibTeX($file);
my @data = map { $obj->toHtml($_); } $obj->getArray();

$css = ($css)?"<link rel=\"stylesheet\" type=\"text/css\" href=\"$css\">\n":"";

print "<html><head>$css<title>Bibliography</title>\n</head>\n<body>\n";
print join("\n",@data);
print "</body></html>\n";
